/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bhvvxtwwrrsdfsxckkql"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodnZ4dHd3cnJzZGZzeGNra3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1MzI4NjUsImV4cCI6MjA4MjEwODg2NX0.kSWNCYlTjqeXFkY0YcGiP647iWiF-dou4us3JZ-FXR8"